### ISSUE TITLE
Why only plain objects are allowed?

### ISSUE THREAD

**Issue by tusharmath** [PolicyStat/object-history#13]
Why do you have this restriction? Every time I have to create a wrapper around my original value which is `boolean` in my case and then use `add`

BTW, this module is AWESOME!

**Comment by mightyiam** [comment]
Hi, Tushar.

Thank you for the praise. I didn't know anyone else was using it.

I wrote it some while ago and I'm still a very fresh developer, so I'm pretty sure that there are some aspects I didn't think of and perhaps I would have done things differently if I had to solve that original question again, now.

And to your point...

I chose an object, because it is kind of the most general data structure in JavaScript.

Supporting other types would add some extra code and I would like to keep it simple.

So, the wrapper around your single value seems to me like a good compromise.

Does this make sense?

**Comment by tusharmath** [comment]
I went through your code, it seems like you are pushing a diff between the
initial and the final states. Probably thats why you cant support primitive
types like date, boolean etc.

**Comment by tusharmath** [comment]
I understand your decision to close the ticket is probably because this is by design and you wouldn't want to change that. For people who end up being on this page, having similar needs, I have created a module [tusharmath/reactive-storage](https://github.com/tusharmath/reactive-storage).

**Comment by mightyiam** [comment]
Your thing seems nice. Also related:
https://github.com/omnidan/redux-undo
